package com.cooksys.backend.model;

// Generated Jun 11, 2015 10:51:11 AM by Hibernate Tools 4.3.1

/**
 * Booking generated by hbm2java
 */
public class Booking implements java.io.Serializable {

	private Integer bookingId;
	private int flightId;
	private int userId;

	public Booking() {
	}

	public Booking(int flightId, int userId) {
		this.flightId = flightId;
		this.userId = userId;
	}

	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	public int getFlightId() {
		return this.flightId;
	}

	public void setFlightId(int flightId) {
		this.flightId = flightId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
