package com.cooksys.frontend.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

// Generated Jun 8, 2015 8:12:32 AM by Hibernate Tools 4.3.1

/**
 * Booking generated by hbm2java
 */

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Booking implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer bookingId;
	private User user;
	private int flightId;

	public Booking() {
	}

	public Booking(User user, int flightId) {
		this.user = user;
		this.flightId = flightId;
	}

	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getFlightId() {
		return this.flightId;
	}

	public void setFlightId(int flightId) {
		this.flightId = flightId;
	}

}
